# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yuanl\Documents\Developer\Inspection Record Consolidating System\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 473)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\yuanl\\Documents\\Developer\\Inspection Record Consolidating System\\images/index.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.leftWidget = QtWidgets.QWidget(self.centralwidget)
        self.leftWidget.setObjectName("leftWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.iconLabel = QtWidgets.QPushButton(self.leftWidget)
        self.iconLabel.setText("")
        self.iconLabel.setIcon(icon)
        self.iconLabel.setIconSize(QtCore.QSize(30, 30))
        self.iconLabel.setObjectName("iconLabel")
        self.verticalLayout.addWidget(self.iconLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.qrCodeButton = QtWidgets.QPushButton(self.leftWidget)
        self.qrCodeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\yuanl\\Documents\\Developer\\Inspection Record Consolidating System\\images/qrcode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qrCodeButton.setIcon(icon1)
        self.qrCodeButton.setIconSize(QtCore.QSize(15, 15))
        self.qrCodeButton.setObjectName("qrCodeButton")
        self.verticalLayout.addWidget(self.qrCodeButton)
        self.commandButton = QtWidgets.QPushButton(self.leftWidget)
        self.commandButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\yuanl\\Documents\\Developer\\Inspection Record Consolidating System\\images/command.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandButton.setIcon(icon2)
        self.commandButton.setIconSize(QtCore.QSize(15, 15))
        self.commandButton.setObjectName("commandButton")
        self.verticalLayout.addWidget(self.commandButton)
        self.settingsButton = QtWidgets.QPushButton(self.leftWidget)
        self.settingsButton.setToolTipDuration(-1)
        self.settingsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\yuanl\\Documents\\Developer\\Inspection Record Consolidating System\\images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon3)
        self.settingsButton.setIconSize(QtCore.QSize(15, 15))
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout.addWidget(self.settingsButton)
        self.gridLayout.addWidget(self.leftWidget, 0, 0, 2, 1)
        self.topWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topWidget.sizePolicy().hasHeightForWidth())
        self.topWidget.setSizePolicy(sizePolicy)
        self.topWidget.setObjectName("topWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.minimizeButton = QtWidgets.QPushButton(self.topWidget)
        self.minimizeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\yuanl\\Documents\\Developer\\Inspection Record Consolidating System\\images/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon4)
        self.minimizeButton.setIconSize(QtCore.QSize(10, 10))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.topWidget)
        self.closeButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\yuanl\\Documents\\Developer\\Inspection Record Consolidating System\\images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon5)
        self.closeButton.setIconSize(QtCore.QSize(10, 10))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.gridLayout.addWidget(self.topWidget, 0, 1, 1, 1)
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleWidget = QtWidgets.QWidget(self.mainWidget)
        self.titleWidget.setObjectName("titleWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.titleWidget)
        self.gridLayout_2.setContentsMargins(10, 6, 10, 2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.subtitleLabel = QtWidgets.QLabel(self.titleWidget)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.gridLayout_2.addWidget(self.subtitleLabel, 2, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.titleWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_2.addWidget(self.titleLabel, 1, 0, 1, 1)
        self.pretitleLabel = QtWidgets.QLabel(self.titleWidget)
        self.pretitleLabel.setObjectName("pretitleLabel")
        self.gridLayout_2.addWidget(self.pretitleLabel, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.titleWidget)
        self.contentWidget = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentWidget.sizePolicy().hasHeightForWidth())
        self.contentWidget.setSizePolicy(sizePolicy)
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 20)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.expressProcessWidget = QtWidgets.QWidget(self.contentWidget)
        self.expressProcessWidget.setObjectName("expressProcessWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.expressProcessWidget)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.expressProcessTitleLabel = QtWidgets.QLabel(self.expressProcessWidget)
        self.expressProcessTitleLabel.setObjectName("expressProcessTitleLabel")
        self.horizontalLayout_2.addWidget(self.expressProcessTitleLabel)
        spacerItem3 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.expressProcessButton = QtWidgets.QPushButton(self.expressProcessWidget)
        self.expressProcessButton.setIcon(icon2)
        self.expressProcessButton.setObjectName("expressProcessButton")
        self.horizontalLayout_2.addWidget(self.expressProcessButton)
        spacerItem4 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.expressProcessWidget)
        self.lastProcessWidget = QtWidgets.QWidget(self.contentWidget)
        self.lastProcessWidget.setObjectName("lastProcessWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.lastProcessWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lastProcessTitleLabel = QtWidgets.QLabel(self.lastProcessWidget)
        self.lastProcessTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessTitleLabel.setObjectName("lastProcessTitleLabel")
        self.verticalLayout_4.addWidget(self.lastProcessTitleLabel)
        self.lastProcessTimeLabel = QtWidgets.QLabel(self.lastProcessWidget)
        self.lastProcessTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessTimeLabel.setObjectName("lastProcessTimeLabel")
        self.verticalLayout_4.addWidget(self.lastProcessTimeLabel)
        self.lastProcessDetailsWidget = QtWidgets.QWidget(self.lastProcessWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastProcessDetailsWidget.sizePolicy().hasHeightForWidth())
        self.lastProcessDetailsWidget.setSizePolicy(sizePolicy)
        self.lastProcessDetailsWidget.setObjectName("lastProcessDetailsWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.lastProcessDetailsWidget)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lastProcessTotalRecordsWidget = QtWidgets.QWidget(self.lastProcessDetailsWidget)
        self.lastProcessTotalRecordsWidget.setObjectName("lastProcessTotalRecordsWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.lastProcessTotalRecordsWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lastProcessTotalRecordsLabel = QtWidgets.QLabel(self.lastProcessTotalRecordsWidget)
        self.lastProcessTotalRecordsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessTotalRecordsLabel.setObjectName("lastProcessTotalRecordsLabel")
        self.verticalLayout_7.addWidget(self.lastProcessTotalRecordsLabel)
        self.lastProcessTotalRecordsTitleLabel = QtWidgets.QLabel(self.lastProcessTotalRecordsWidget)
        self.lastProcessTotalRecordsTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessTotalRecordsTitleLabel.setObjectName("lastProcessTotalRecordsTitleLabel")
        self.verticalLayout_7.addWidget(self.lastProcessTotalRecordsTitleLabel)
        self.horizontalLayout_3.addWidget(self.lastProcessTotalRecordsWidget)
        self.lastProcessValidRecordsWidget = QtWidgets.QWidget(self.lastProcessDetailsWidget)
        self.lastProcessValidRecordsWidget.setObjectName("lastProcessValidRecordsWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.lastProcessValidRecordsWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lastProcessValidRecordsLabel = QtWidgets.QLabel(self.lastProcessValidRecordsWidget)
        self.lastProcessValidRecordsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessValidRecordsLabel.setObjectName("lastProcessValidRecordsLabel")
        self.verticalLayout_6.addWidget(self.lastProcessValidRecordsLabel)
        self.lastProcessValidRecordsTitleLabel = QtWidgets.QLabel(self.lastProcessValidRecordsWidget)
        self.lastProcessValidRecordsTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessValidRecordsTitleLabel.setObjectName("lastProcessValidRecordsTitleLabel")
        self.verticalLayout_6.addWidget(self.lastProcessValidRecordsTitleLabel)
        self.horizontalLayout_3.addWidget(self.lastProcessValidRecordsWidget)
        self.lastProcessAttachmentsCountWidget = QtWidgets.QWidget(self.lastProcessDetailsWidget)
        self.lastProcessAttachmentsCountWidget.setObjectName("lastProcessAttachmentsCountWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.lastProcessAttachmentsCountWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lastProcessAttachmentsCountLabel = QtWidgets.QLabel(self.lastProcessAttachmentsCountWidget)
        self.lastProcessAttachmentsCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessAttachmentsCountLabel.setObjectName("lastProcessAttachmentsCountLabel")
        self.verticalLayout_5.addWidget(self.lastProcessAttachmentsCountLabel)
        self.lastProcessAttachmentsCountTitleLabel = QtWidgets.QLabel(self.lastProcessAttachmentsCountWidget)
        self.lastProcessAttachmentsCountTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastProcessAttachmentsCountTitleLabel.setObjectName("lastProcessAttachmentsCountTitleLabel")
        self.verticalLayout_5.addWidget(self.lastProcessAttachmentsCountTitleLabel)
        self.horizontalLayout_3.addWidget(self.lastProcessAttachmentsCountWidget)
        self.verticalLayout_4.addWidget(self.lastProcessDetailsWidget)
        self.verticalLayout_3.addWidget(self.lastProcessWidget)
        self.verticalLayout_2.addWidget(self.contentWidget)
        self.gridLayout.addWidget(self.mainWidget, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "统计与汇总系统"))
        self.qrCodeButton.setToolTip(_translate("MainWindow", "连接到 App"))
        self.commandButton.setToolTip(_translate("MainWindow", "串口通信"))
        self.settingsButton.setToolTip(_translate("MainWindow", "设置"))
        self.subtitleLabel.setText(_translate("MainWindow", "Inspection Records Consolidating System"))
        self.titleLabel.setText(_translate("MainWindow", "检查记录统计汇总系统"))
        self.pretitleLabel.setText(_translate("MainWindow", "西安地铁服务监督员"))
        self.expressProcessTitleLabel.setText(_translate("MainWindow", "快速处理"))
        self.expressProcessButton.setText(_translate("MainWindow", "开始"))
        self.lastProcessTitleLabel.setText(_translate("MainWindow", "上次处理"))
        self.lastProcessTimeLabel.setText(_translate("MainWindow", "2020-01-01 00:00:01"))
        self.lastProcessTotalRecordsLabel.setText(_translate("MainWindow", "200"))
        self.lastProcessTotalRecordsTitleLabel.setText(_translate("MainWindow", "全部记录"))
        self.lastProcessValidRecordsLabel.setText(_translate("MainWindow", "200"))
        self.lastProcessValidRecordsTitleLabel.setText(_translate("MainWindow", "有效记录"))
        self.lastProcessAttachmentsCountLabel.setText(_translate("MainWindow", "200"))
        self.lastProcessAttachmentsCountTitleLabel.setText(_translate("MainWindow", "匹配附件"))
